### ISSUE TITLE
centos6无法使用

### ISSUE THREAD

**Issue by huawuhen** [xratzh/CBBR#1]
测试多个vps商的centos6 32&64 第一步走完后，重启便死在boot那里，应该是内核问题。

**Comment by xratzh** [comment]
@huawuhen 在阿里云新加坡上面测试通过，其余未知。已经稍微修复，请尝试，或者更换系统为7

**Comment by xratzh** [comment]
/boot/grub/grub.conf里面default=0改为default=1（内核排序，第一个为0，后面依次为1、2、3......）默认选择从0内核启动，需要更改为制定内核启动。之后保存重启
