### ISSUE TITLE
ubuntu 18.04 x86_64  ERROR!SECOND SETP!

### ISSUE THREAD

**Issue by ghost** [xratzh/CBBR#3]
https://raw.githubusercontent.com/nanqinlang/tcp_nanqinlang-test/master/tcp_nanqinlang.c
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 36157 (35K) [text/plain]
Saving to: ‘./tcp_bbr_powered.c’

./tcp_bbr_powered.c    100%[===========================>]  35.31K  --.-KB/s    in 0.001s  

2018-05-17 05:31:47 (44.5 MB/s) - ‘./tcp_bbr_powered.c’ saved [36157/36157]

Install error.

**Comment by xratzh** [comment]
抱歉，暂时没有适配18.04，请更换为16.04的64位版本。过几天有时间再搞18.04的。

**Comment by ghost** [comment]
好的，谢谢你

**Comment by xratzh** [comment]
已经更新ubuntu18的魔改bbr
