### ISSUE TITLE
怎么检查bbr魔改的状态是否正常运行？

### ISSUE THREAD

**Issue by livermio** [xratzh/CBBR#4]
刚开始用的时候速度很快这两天突然掉到几百kb了油管，我想查看一下运行状态是否正常，还是小鸡抽了

**Comment by xratzh** [comment]
@nilkkkk lsmod |grep -q 'bbr_powered'，有内容返回就是正常运行

**Comment by yuukiyuuna** [comment]
> @nilkkkk lsmod |grep -q 'bbr_powered'，有内容返回就是正常运行

如果没有返回结果呢，这个该怎么开启

**Comment by sininit** [comment]
执行   lsmod | grep bbr
