### ISSUE TITLE
centos 7 直接GG,

### ISSUE THREAD

**Issue by rustxj** [xratzh/CBBR#5]
新独立服务器 安装 CBBR 直接挂掉了，服务器启都起步动不了。

版本：

=============
[root@caesardata ~]# cat /etc/issue

  CentOS Linux 7 (Core)

  Linux caesardata 4.9.124-xxxx-std-ipv6-64 #346072 SMP Wed Aug 29 07:54:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

  Server	: 908416
  IPv4		: XXXXXXXXXX
  IPv6		: XXXXXXXXXX
  Hostname	: caesardata
=====================================

**Comment by xratzh** [comment]
我目前唯一在尝试的就是阿里云国际版，还有搬瓦工的系统，其他系统难以保证都能适用
