### ISSUE TITLE
这样算成功了吗

### ISSUE THREAD

**Issue by liweishu** [xratzh/CBBR#7]
sysctl net.ipv4.tcp_available_congestion_control
返回结果
net.ipv4.tcp_available_congestion_control = bbr_powered bbr cubic reno

**Comment by liweishu** [comment]
lsmod |grep -q 'bbr_powered' 没有结果
lsmod |grep 'bbr_powered' 返回 tcp_bbr_powered        20480  5
lsmod |grep -q 'bbr_powered' 始终没有结果
lsof -i 结果里没有 bbr_powered 项

**Comment by xratzh** [comment]
成功的
